# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Major < Formula
  desc "Major CLI"
  homepage "https://github.com/major-technology/major"
  version "0.2.27"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://major-cli-releases.s3.us-west-1.amazonaws.com/0.2.27/major_0.2.27_darwin_amd64.tar.gz"
      sha256 "80a7728990dbe55ba322bbbf3d3f60a62a5269ab536488e9001d7f231f93049d"

      def install
        bin.install "major"
      end
    end
    if Hardware::CPU.arm?
      url "https://major-cli-releases.s3.us-west-1.amazonaws.com/0.2.27/major_0.2.27_darwin_arm64.tar.gz"
      sha256 "dcf5a02b6b3191e9a29090f3e057cb7a41aeb83cbc1ec1f0ec2a18e565a04d83"

      def install
        bin.install "major"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://major-cli-releases.s3.us-west-1.amazonaws.com/0.2.27/major_0.2.27_linux_amd64.tar.gz"
      sha256 "ff165dfab7866e1b304bd3a18e225bec1e85a99183826b988248eddea6fba464"
      def install
        bin.install "major"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://major-cli-releases.s3.us-west-1.amazonaws.com/0.2.27/major_0.2.27_linux_arm64.tar.gz"
      sha256 "464c0d89af6a01074fdbc2dc31c36cb13aee42ef9f2de9d4ddd4ec88bffd5cac"
      def install
        bin.install "major"
      end
    end
  end

  test do
    system "#{bin}/major", "--version"
  end
end
